### ISSUE TITLE
Need to pass temperature in multiple places

### ISSUE THREAD

**Issue by jqhoogland** [timaeus-research/devinterp#88]
You need to pass a temperature in both the callbacks and the optim_kwargs. We should give a warning if the user only provides one or the other.

**Comment by jqhoogland** [comment]
One of the examples may currently leave out the temperature, thus default to a value and confuse users

**Comment by wz-ml** [comment]
Looks like `nbeta` is now a required parameter in the callbacks that take them: `LLCEstimator` and `MalaAcceptanceRate`. I've added print notices in `sample` and `estimate_learning_coeff_with_summary` for both directions, just in case this changes. See [PR #93 ](https://github.com/timaeus-research/devinterp/pull/93).
