### ISSUE TITLE
GradientNorm and NoiseNorm callbacks use incorrect SGLD gradient / noise

### ISSUE THREAD

**Issue by svwingerden** [timaeus-research/devinterp#90]
in [`devinterp.slt.norms`](https://github.com/timaeus-research/devinterp/blob/main/src/devinterp/slt/norms.py), the GradientNorm and NoiseNorm use `param.grad` and `optimizer.noise` respectively, but this should be multiplied by `0.5 * group["lr"]` and `group["lr"] ** 0.5` respectively to get the actual gradient and noise updates from SGLD.

**Comment by wz-ml** [comment]
Resolved in PR #93 .
